version: '3'
services:
  back-service:
    image: foucaulde/flaskrepo:1.0
    ports:
      - "5000:5000"
    environment:
      - CURRENT_ENVIRONMENT=development

  front-service:
    image: foucaulde/repofrontflask:1.0
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=http://back-service:5000